### ISSUE TITLE
Improve Components

### ISSUE THREAD

**Issue by tadhglewis** [tadhglewis/issue-status#13]
Possible improvements
- Add tooltip to components (this can pull the body of the component issue)
- Make components linkable (will need to find somewhere to pull a url from)
- Make component groups (ie website and inside the website group you have CDN, API, etc)

Still deciding on whether above improvements should be done.

If you are interested in this GitHub Issue leave a comment so I can put this as priority.

**Comment by D3nn7** [comment]
In our fork of your awesome issue-status I have implemented the possibility to click on an incident. When you click such an link, it will refer you to the GitHub issue with all future information about the incident.

If you want, I can create a PR of this fork for you here.

**Comment by tadhglewis** [comment]
@D3nn7 thanks! I am looking at upstreaming this feature - either linking to github or having an internal route which wraps github issue comments as updates :)
