### ISSUE TITLE
Hi how can i setup it?

### ISSUE THREAD

**Issue by ririko5834** [tadhglewis/issue-status#23]
Hi i cloned repo, edited .env and i see same status page as this https://tadhglewis.github.io/issue-status/
I tried to run `npm run build`  and `npm run deploy`
![image](https://user-images.githubusercontent.com/64729293/93737278-08ae2580-fbe3-11ea-9650-e3c8488fdf2b.png) but it didnt work

**Comment by tadhglewis** [comment]
@ririko5834 This seems like an unrelated issue caused by the amount of RAM available on your computer.

Could you please let me know how much RAM you have available when running `npm run deploy`?

**Comment by ririko5834** [comment]
Hi, i tried to run this command on repl with 500 mb RAM on free plan. Ik its not enough to run it.
Now i decided that i want another status page that can be hosted on netlify with 1 click. This one: https://github.com/weeblrpress/clearstatus/
I followed setup guide but i am getting This error when i go to status.mydomain.com/admin
![image](https://user-images.githubusercontent.com/64729293/93857213-8f820180-fcba-11ea-9d52-c6acc027110a.png)
Idk why i am getting this. I followed setup guide and i did not changed anything in repo

**Comment by tadhglewis** [comment]
@ririko5834 My understanding is repl is a cloud dev environment? I would suggest running `npm run deploy` on your local machine, once that is done you won't need to do it again except when updating. I may look into adding a deploy on netlify button to Issue Status if people want it or if I have a need

Regarding that other status page, I'm not too sure as this is unrelated to this project. I'm assuming you are missing some config details based off the error

**Comment by ririko5834** [comment]
> Regarding that other status page, I'm not too sure as this is unrelated to this project. I'm assuming you are missing some config details based off the error

Yes, but i followed video tutorial https://www.youtube.com/watch?v=wFF2OBPfalQ so idk whats wrong

> I may look into adding a deploy on netlify button to Issue Status if people want it or if I have a need
Yes, please add it, many people like one-click netlify deploy button 👍

**Comment by ririko5834** [comment]
Also can you please add system description
