### ISSUE TITLE
Installation on Plesk and requirements

### ISSUE THREAD

**Issue by officialLucas** [tadhglewis/issue-status#41]
Hello,
is it possible to install the site on Plesk?
Could you perhaps list minimum requirements for installation on the GitHub page?

**Comment by tadhglewis** [comment]
As this is just a web app, it can run on any web server.

The minimum requirements is a web server that can serve html and css.

**Comment by officialLucas** [comment]
Hey, thank you for the fast answer.
After editing the .env file on my Plesk webspace, where do I run the "**npm run build**" command?
