### ISSUE TITLE
Unknown problem.

### ISSUE THREAD

**Issue by sudis** [tadhglewis/issue-status#42]
Hello there! I am trying to use your Status page. But I am having big problems. Coming to my problem, when I translate some of the content into my own language, the Status texts turn into Unknown (in translated language: "Bilinmiyor").

Despite the transformation, everything is running smoothly in the main status.

![Problem pic](https://cdn.discordapp.com/attachments/815553030099173376/863064441024413726/Zrzut_ekranu_2021-07-9_o_16.29.18.png)

Eftelya is `performance issues` and Tracer is `operational` but as you see that's not works. 

There are two files that I translated. 

![enter image description here](https://cdn.discordapp.com/attachments/815553030099173376/863065153963819018/Zrzut_ekranu_2021-07-9_o_16.32.22.png)

I made the changes I made in one file in the second file. I also paid attention to all the quotation marks in the `map` file, which is more complicated than the other. I have a few days to deal with this situation. It would be great if you could get back to me early.

Sincerely,
Magdalena Sude.

**Comment by sudis** [comment]
I just tried to translate from the original file. (Via SRC.) Unknown error still persists.

**Comment by sudis** [comment]
I did a little test to see if the problem is with Turkish characters. In vain then.

![Turkish letters](https://cdn.discordapp.com/attachments/833767064397283409/863083211436589118/Zrzut_ekranu_2021-07-9_o_17.43.37.png)

**Comment by tadhglewis** [comment]
Hi @sudis, could you upload your source code somewhere? looks like only the compiled site is in the repo https://github.com/sudis/serendia-status.

It's likely that you changed https://github.com/tadhglewis/issue-status/blob/master/src/components/components/component/statuses.js ?

If so, the text in the 'name' is used when comparing to the 'labels' attached to a GitHub Issue.

Looking at your repository, https://github.com/sudis/serendia-status/issues/2 has the label 'performance issues' when it should be 'eftelya'.

I would need to see the source code to do any proper debugging though. Let me know if this solves your issue.
