### ISSUE TITLE
Markdown support broken

### ISSUE THREAD

**Issue by wtfcxt** [tadhglewis/issue-status#43]
Hey!
Looks like Markdown isn't working in Incidents (not even on your demo site, https://tadhglewis.github.io/issue-status/). maybe it's worth fixing?
~ cxt

![grafik](https://user-images.githubusercontent.com/53837207/128399008-38a6bb4e-b24b-4f01-94eb-b4be86731746.png)

**Comment by tadhglewis** [comment]
I added support for markdown but never did a release.

I have released version 1.1.0.

You should be able to pull the latest version and repush your status page to get the latest feature

You may need to do some changes as per breaking changes on https://github.com/tadhglewis/issue-status/releases/tag/1.1.0

**Comment by wtfcxt** [comment]
![grafik](https://user-images.githubusercontent.com/53837207/128537041-6ce4bcf5-4347-4690-a85b-48694707fd7c.png)

**Comment by tadhglewis** [comment]
@wtfcxt you should be able to follow this https://github.com/tadhglewis/issue-status#update to sync your repo with tadhglewis/issue-status.

Then simply follow the steps for deploying

**Comment by wtfcxt** [comment]
perfect
