### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by KjellDE** [tadhglewis/issue-status#46]
Hello.

I'm trying to run issue status on my own website/domain, but I don't really understand how to setup and where to run commands like "npm run build" etc.
I don't use GitHub often.

Detailed instructions would be very helpful, thanks!

**Comment by tadhglewis** [comment]
You will need to follow https://github.com/tadhglewis/issue-status#setup and then https://github.com/tadhglewis/issue-status#github-pages

You run this command in Terminal.
