### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by LaudyTV** [tadhglewis/issue-status#52]
following the steps you provide "npm run build" won't work because there are no "react-scripts" in there

You first need to run "npm install"

Otherwise nothing will happen :)

**Comment by Kalmai221** [comment]
I tried that but Github pages version, I tried but it always shown errors

**Comment by EinKilian** [comment]
Did you install node.js to your pc?

**Comment by tadhglewis** [comment]
Added note about pre-req for installing node and now also pnpm
