### ISSUE TITLE
blank website

### ISSUE THREAD

**Issue by EinKilian** [tadhglewis/issue-status#65]
Hey! I recently did set up your issue. Now I connected my gh-pages to GutHubPages and when I'm going to open my website it's a plank white website. And I don't know where is there an issue.

**Comment by EinKilian** [comment]
[
<img width="721" alt="image" src="https://user-images.githubusercontent.com/92912642/176907105-1fe414b9-393e-486c-adaf-190c47e4e652.png">
](url)

**Comment by tadhglewis** [comment]
@EinKilian can you link the repo?

**Comment by tadhglewis** [comment]
@EinKilian I can see it is trying to make requests to `https://api.github.com/repos/oneliferp/status.oneliferp.net/issues?state=all&labels=issue%20status,component`

I can also see you've changed the repo name to `Website_Statuspage` as per https://github.com/oneliferp/Website_Statuspage/blob/master/.env#L7

However it doesn't look like you've re-deployed these changes as the last update on `gh-pages` branch was 10 days ago - https://github.com/oneliferp/Website_Statuspage/tree/gh-pages

Re-deploying will fix the issue.

**Comment by EinKilian** [comment]
I renamed the repo to `status.oneliferp.net` and I did re-deploying `gh-pages`. After that I tryed the pages and added normaly my cname. Still an blank website.

Maybe there is another issue with the code.. maybe I did somethink wrong.

**Comment by EinKilian** [comment]
Huh.. okay wait. How?
![github-issue](https://user-images.githubusercontent.com/92912642/178416103-c59eeb58-394c-44f6-9785-ed78489be8fa.gif)

**Comment by EinKilian** [comment]
Now its gone. Im sorry, but I don't get it..

**Comment by EinKilian** [comment]
Nah okay. I think its working now.

https://status.oneliferp.net/

**Comment by EinKilian** [comment]
Thanks for your help! I appreciate it <3
