### ISSUE TITLE
Cant see the description in de incident issues

### ISSUE THREAD

**Issue by NOOBBase** [tadhglewis/issue-status#67]
Hi,

when creating an issue with the incident label. The title is shown but not the content of the description

<img width="1119" alt="Screenshot 2022-07-11 at 15 32 04" src="https://user-images.githubusercontent.com/84967231/178275845-620ad9e7-fccc-464c-9c5a-479350e73332.png">

**Comment by NOOBBase** [comment]
@tadhglewis https://github.com/JustFlows/CustomerSupport/issues/10

**Comment by NOOBBase** [comment]
Hi @tadhglewis,

Knowing you most probably are very busy. Adding this friendly reminder to the board :)

**Comment by tadhglewis** [comment]
@NOOBBase this was a bug due to a dependency updating. I pushed a fix.

You will need to pull in any changes to your repo and redeploy to GitHub Pages
