### ISSUE TITLE
[Question] Public or provate repo?

### ISSUE THREAD

**Issue by collimarco** [tadhglewis/issue-status#77]
Do you need to use a private or public repo on GitHub?

And, if it's a public repo, can anyone open an issue and this will appear on the status page? I don't understand this.

**Comment by tadhglewis** [comment]
@collimarco The repo containg the code does not matter whether it's public or private however you do need a public repo for the GitHub issues.

Although anyone can create a GitHub issue, only users with permission can add labels and the site filters down to only issues with the label of `issue status`. See https://github.com/tadhglewis/issue-status?tab=readme-ov-file#details for more details
